# Generated by Django 4.1.5 on 2023-01-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_listing", models.CharField(max_length=200)),
                ("food_quantity", models.IntegerField(default=1)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=10000)),
                (
                    "expiration_date",
                    models.DateTimeField(verbose_name="date published"),
                ),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("prepackaged", models.BooleanField(blank=True, null=True)),
                ("perishable", models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
