# Generated by Django 4.1.5 on 2023-02-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PickMyWaste", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="donators", name="pub_date",),
        migrations.AlterField(
            model_name="food",
            name="description",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="food",
            name="expiration_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="food",
            name="pub_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
