# Generated by Django 4.1.5 on 2023-02-03 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PickMyWaste", "0004_alter_food_donator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="donator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="PickMyWaste.donators",
            ),
        ),
    ]
