# Generated by Django 4.1.5 on 2023-02-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PickMyWaste", "0007_donators_email_alter_donators_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="donators",
            name="latitude",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="donators",
            name="longitude",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="donators",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
