# Generated by Django 4.1.5 on 2023-02-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PickMyWaste", "0008_donators_city_donators_country_donators_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donators",
            name="latitude",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="donators",
            name="longitude",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
