# Generated by Django 4.1.5 on 2023-02-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PickMyWaste", "0009_donators_city_donators_country_donators_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="donators", name="latitude",),
        migrations.RemoveField(model_name="donators", name="longitude",),
    ]
