# Generated by Django 4.1.5 on 2023-02-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PickMyWaste", "0009_donators_latitude_donators_longitude"),
    ]

    operations = [
        migrations.RemoveField(model_name="donators", name="city",),
    ]
