# Generated by Django 4.1.5 on 2023-02-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PickMyWaste", "0003_donators_name_food_donator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="donator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="PickMyWaste.donators",
            ),
        ),
    ]
