# Generated by Django 4.1.5 on 2023-02-09 03:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("PickMyWaste", "0006_remove_donators_food_listing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donators",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="donators",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
